### ISSUE TITLE
Semantic Mask

### ISSUE THREAD

**Issue by ldkong1205** [happychenpipi/EventSAM#1]
Hi @happychenpipi @ZHU-Zhiyu, thanks for sharing your work, it looks very interesting!

Regarding the collected RGB-Event dataset:
- Does it associate with the semantic mask or just the class-agnostic instance mask?
- Have you tried EventSAM on ESS datasets? Such as DDD17-Seg and DSEC-Semantic.

**Comment by ZHU-Zhiyu** [comment]
Hi @ldkong1205, Thanks very much for your interest.
1) The dataset only contains the class-agnostic segmentation results from the original SAM. The semantic meaning of each segment may be obtained from current large vision-language models.
2) That's a good point. We will try to evaluate them on DDD17-Seg and DSEC-Semantic.

**Comment by ldkong1205** [comment]
Hi @ZHU-Zhiyu, thanks for your answers, they are very helpful!

I have another two questions:
- I am not very familiar with class-agnostic segmentation. How do you map with the ground truth masks for the generated class-agnostic masks? Is it at the instance level or pixel level?
- Will you open-source the code for the baseline models as well? Such as DTL and EVDistill.

**Comment by ZHU-Zhiyu** [comment]
@ldkong1205 Thanks for the question.
1) In the testing phase, we take each segment of the ground truth (GT) mask and calculate the IOU with the most overlapped counterpart from model prediction (i.e., the one with the highest IOU). Finally, average all segments.
[code of metric](evaluate/calculate_metric.py)
2) No problem. We will make plans to release those baseline models.

**Comment by ldkong1205** [comment]
Thanks for you reply~
