### ISSUE TITLE
About DSEC results

### ISSUE THREAD

**Issue by Candy-Crusher** [happychenpipi/EventSAM#5]
Hi dear authors,

may I ask where are the results for DSEC-SEG dataset? I didn't see them in the paper

**Comment by happychenpipi** [comment]
The experimental results of DDD17-SEG and DSEC-SEG were newly added during the paper's rebuttal process. Additionally, we have included these relevant contents in the supplementary materials of the camera-ready version.

**Comment by SchuckLee** [comment]
Thank you for your previous response regarding the DSEC-SEG results. However, I couldn't find the DSEC-SEG results in the supplementary materials provided at [this link](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Chen_Segment_Any_Event_CVPR_2024_supplemental.pdf).

Could you kindly point me to the correct version or location where the results for the DSEC-SEG dataset are available?

Thanks a lot for your help!

> The experimental results of DDD17-SEG and DSEC-SEG were newly added during the paper's rebuttal process. Additionally, we have included these relevant contents in the supplementary materials of the camera-ready version.

**Comment by zhiwen-xdu** [comment]
We show the results of DDD17-SEG and DSEC-SEG below. Note that the model weights are the same as in the paper. 

| DDD17-SEG | mP | mR | $\mathrm{mIoU}(\uparrow)$ | $\mathrm{aIoU}(\uparrow)$ | DSEC-SEG | mP | mR | $\mathrm{mIoU}(\uparrow)$ | $\mathrm{aIoU}(\uparrow)$ |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| ETNet [1] | 0.42 | 0.77 | 0.34 | 0.50 | ETNet [1] | 0.47 | 0.73 | 0.36 | 0.56 |
| Ours | $\mathbf{0 . 5 9}$ | 0.62 | $\mathbf{0 . 3 7}$ | $\mathbf{0 . 5 1}$ | Ours | $\mathbf{0 . 5 0}$ | 0.72 | $\mathbf{0 . 3 8}$ | $\mathbf{0 . 5 7}$ |


[1] Weng W, Zhang Y, Xiong Z. Event-based video reconstruction using transformer[C]//Proceedings of the IEEE/CVF International Conference on Computer Vision. 2021: 2563-2572.

**Comment by HeinZingerRyo** [comment]
Hi @zhiwen-xdu,

Thanks for presenting this result. I would like to know whether these are the results of instance segmentation or semantic segmentation. It seems that both DDD17 and DSEC datasets only provide semantic masks.
