### ISSUE TITLE
MVSEC GT

### ISSUE THREAD

**Issue by AiladReb** [happychenpipi/EventSAM#6]
Hey,
Where can I find the segmentation semantic of MVSEC GT ?

**Comment by happychenpipi** [comment]
This work focuses on class-agnostic scene segmentation. For the semantic segmentation mask, you can refer to other works, such as ESS: Learning Event based Semantic Segmentation from Still Images. Meanwhile, I observed that these semantic segmentation masks are typically generated using readily available segmentation models applied to images.
