### ISSUE TITLE
Question about event npz file

### ISSUE THREAD

**Issue by Bin1119** [happychenpipi/EventSAM#8]
Hello, I tried to use numpy to read the raw npz data of the event you provided, but I found that some npz files would report errors:
```
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
Such as 
'''
Datasets/RGBE-SEG/train/dvSave-2022_02_07_22_44_25/event/0195.npz
Datasets/RGBE-SEG/train/dvSave-2022_02_07_22_44_25/event/0223.npz
Datasets/RGBE-SEG/train/dvSave-2022_02_07_22_44_25/event/0194.npz
Datasets/RGBE-SEG/train/dvSave-2022_02_07_22_44_25/event/0227.npz
.........
'''
Even if allow_pickle=True, these files will still read errors. I wonder if you use numpy when saving npz files? Can you read these files normally?
Thanks

**Comment by suizhipeng** [comment]
I am very curious about how to convert the `.npz` files in the `event/` directory into `.jpg` files in the `event_image/` directory. Have you managed to address this issue?

**Comment by suizhipeng** [comment]
Thank you for your excellent work, I noticed that the image used in the training is the 3-channel time-voxel image, could you provide the code to convert the raw event data into three-channel voxel?  Thanks very much.
